name: Mirror FFmpeg & yt-dlp Binaries

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get install -y jq unzip xz-utils

      - name: Fetch latest FFmpeg release info
        run: |
          curl -s https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest > ffmpeg_latest.json

      - name: Fetch latest yt-dlp release info
        run: |
          curl -s https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest > ytdlp_latest.json

      # ---------- FFmpeg: Linux ----------
      - name: Download & extract FFmpeg (Linux)
        run: |
          URL=$(jq -r '.assets[].browser_download_url | select(contains("master-latest-linux64-lgpl") and (contains("-shared") | not))' ffmpeg_latest.json)
          curl -L "$URL" -o ffmpeg-linux.tar.xz
          mkdir -p bin/linux
          tar -xJf ffmpeg-linux.tar.xz --strip-components=1 -C bin/linux
          mv bin/linux/bin/ffmpeg bin/linux/ffmpeg
          mv bin/linux/bin/ffprobe bin/linux/ffprobe
          rm -rf bin/linux/bin bin/linux/presets

      # ---------- FFmpeg: Windows ----------
      - name: Download & extract FFmpeg (Windows)
        run: |
          URL=$(jq -r '.assets[].browser_download_url | select(contains("master-latest-win64-lgpl") and (contains("-shared") | not))' ffmpeg_latest.json)
          curl -L "$URL" -o ffmpeg-win.zip
          mkdir -p bin/windows
          unzip -q ffmpeg-win.zip -d temp
          mv temp/*/bin/ffmpeg.exe bin/windows/
          mv temp/*/bin/ffprobe.exe bin/windows/
          rm -rf temp

      # ---------- yt-dlp ----------
      - name: Download yt-dlp binaries
        run: |
          LINUX_URL=$(jq -r '.assets[].browser_download_url | select(endswith("yt-dlp_linux"))' ytdlp_latest.json)
          WIN_URL=$(jq -r '.assets[].browser_download_url | select(endswith("yt-dlp.exe"))' ytdlp_latest.json)

          mkdir -p bin/linux bin/windows
          curl -L "$LINUX_URL" -o bin/linux/yt-dlp
          curl -L "$WIN_URL" -o bin/windows/yt-dlp.exe

      # ---------- Cleanup and hashes ----------
      - name: Compute SHA256 checksums
        run: |
          cd bin
          find . -type f -exec sha256sum {} \; > SHA256SUMS.txt
          cd ..

      - name: Commit & push updates
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add bin
          git commit -m "Update FFmpeg & yt-dlp binaries" || echo "No changes to commit"
          git push
